all:
  vars:
    osp:
      resource_path: /osp/temp

      packstack:
        CONFIG_DEFAULT_PASSWORD: openstack
        CONFIG_KEYSTONE_ADMIN_PW: openstack
        CONFIG_CINDER_VOLUMES_SIZE: 300G
        CONFIG_SERVICE_WORKERS: 4
        CONFIG_NTP_SERVERS:
        CONFIG_CEILOMETER_INSTALL: n
        CONFIG_HEAT_INSTALL: y
        CONFIG_PROVISION_DEMO: n
        CONFIG_NEUTRON_OVS_BRIDGE_MAPPINGS: physnet1:br-ex
  
      network:
        nic: eno1
        cidr: 192.168.1.0/24
        dns: 192.168.1.1
        dhcp:
          start: 192.168.1.20
          end: 192.168.1.90

  children:
    osp:
      hosts:
        openstack.example.com:
          ansible_connection: local
